# site settings
title: Fansub Imaji
author: imajisubs
description: Bukan Fansub Basa-Basi
url: "https://fansubimaji.github.io"
permalink: /:title

# post settings
tv_thumb: ""
movie_thumb: ""
bd_thumb: ""
not_thumb: "https://raw.githubusercontent.com/fansubimaji/fansubimaji.github.io/master/img/404_thumb.png"

# others
timezone: Asia/Jakarta
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

# plugins
plugins:
  - jekyll-feed
